export const supportedLocales = ['zh-CN', 'en'] as const;

export type AppLocale = (typeof supportedLocales)[number];

/** Presentation only: domain validation messages remain locale independent. */
export function translateGenerationConnectionError(locale: AppLocale, message: string): string {
  if (locale !== 'zh-CN') return message;
  const messages: Record<string, string> = {
    'Source and generation nodes must exist on the same board.': '素材与生成节点必须位于同一画板。',
    'Text-only generation cannot accept image connections. Choose an image task first.':
      '文生创意不接受图片连线，请先切换到图像任务。',
    'Only visual source nodes can be connected to generation.':
      '只能连接图片、草图、设计方案或候选结果。',
    'Generation connections cannot create a cycle.': '不能创建循环连接。',
    'This source is already connected.': '这份素材已经连接，无需重复连接。',
    'Only one main image can be connected.': '只能连接一张主图，请先移除已有主图。',
    'At most four additional references can be connected.': '最多连接四张补充参考图。',
  };
  return messages[message] ?? message;
}

const englishMessages = {
  'views.title': 'View set',
  'decision.next': 'Change decision status',
  'decision.save': 'Save decision',
  'decision.hint':
    'A local designer decision only; it does not certify manufacturability or run AI.',
  'decision.failed': 'Could not save. The design may have changed; reopen it and retry.',
  'decision.archiveConfirm':
    'Archive this design? This is a terminal decision status in this version. Images, descendants and canvas cards will not be deleted.',
  'decision.archived':
    'Archived. This version does not reopen archived decisions; the design and its images remain available.',
  'design.createVariant': 'Create manual variant',
  'design.createConcept': 'Create concept from this image',
  'design.conceptName': 'Concept name',
  'design.manualConceptHint':
    'Reuse this reference image or saved sketch preview as a concept. The original card stays; no AI request or ownership claim is made.',
  'design.conceptFailed':
    'Could not create the concept. Check that the image or saved sketch preview is available, then retry.',
  'design.variantName': 'Variant name',
  'design.manualVariantHint':
    'Create a child design with the current preview and design constraints. No new image or AI request; the source stays unchanged.',
  'design.variantFailed': 'Could not create the variant. Your name is retained; please retry.',
  'cmf.title': 'CMF alternatives',
  'cmf.choose': 'Choose CMF set',
  'cmf.new': 'New CMF set',
  'cmf.name': 'Name',
  'cmf.alternative': 'Alternative',
  'cmf.material': 'Material',
  'cmf.finish': 'Finish',
  'cmf.notes': 'Notes',
  'cmf.colorName': 'Color name',
  'cmf.hex': 'Color HEX',
  'cmf.texture': 'Texture image',
  'cmf.remove': 'Remove alternative',
  'cmf.add': 'Add alternative',
  'cmf.save': 'Save CMF set',
  'cmf.saved': 'CMF set saved.',
  'cmf.failed': 'CMF could not be saved. Your draft is retained; please retry.',
  'cmf.hint':
    'Local design records only. Saving does not render images or run AI. Up to 24 alternatives; the canvas previews the first four. Texture images are references, not applied 3D materials.',
  'views.choose': 'Choose view set',
  'views.new': 'New view set',
  'views.place': 'Save and place on this board',
  'views.name': 'View set name',
  'views.hint':
    'Assign saved images from this board. Save locally without AI or changes to design lineage. Adopt candidates first.',
  'views.empty': 'No image',
  'views.retained': 'Saved image',
  'views.front': 'Front',
  'views.rear': 'Rear',
  'views.left': 'Left',
  'views.right': 'Right',
  'views.top': 'Top',
  'views.bottom': 'Bottom',
  'views.perspective': 'Perspective',
  'views.save': 'Save view set',
  'views.saved': 'View set saved.',
  'views.failed': 'Could not save. Your draft is retained; try again.',
  'language.label': 'Language',
  'language.zh-CN': '简体中文',
  'language.en': 'English',
  'common.add': 'Add',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'materials.title': 'Local materials',
  'research.title': 'Research collections',
  'research.analyze': 'Analyze selected research',
  'research.selected': 'Selected records: {count}',
  'research.analyzeHint':
    'Select 1–8 records, then review their images and text before sending. User-supplied claims are unverified. Source links are not fetched. Text-only records use text analysis; images require vision support.',
  'research.review': 'Review selected evidence',
  'research.sent':
    'Will send {count} records and {images} distinct images, plus your question. Only the records shown below are included.',
  'research.analysisError':
    'Analysis failed. Check that records have not changed, images are available and the provider supports this input. No automatic retry or text-only fallback was made.',
  'research.importImage': 'Import image into collection',
  'research.importError':
    'Image import failed. Use a valid PNG, JPEG, WebP, GIF or AVIF up to 25 MB and 32 megapixels. If research changed elsewhere, reload before retrying.',
  'research.search': 'Search research, tags, brands or products',
  'research.hint':
    'Collect your own images, links and notes. Everything stays local and is included in project exports. No web scraping or automatic AI requests. Do not store credentials or private information here.',
  'research.addEntry': 'Add research',
  'research.addCollection': 'New collection',
  'research.reload': 'Reload saved research',
  'research.collection': 'Collection',
  'research.all': 'All research',
  'research.editCollection': 'Edit collection and members',
  'research.deleteCollection': 'Delete collection',
  'research.deleteCollectionHint':
    'Delete this collection only? Research entries, images and designs are retained.',
  'research.deleteEntryHint':
    'Delete this research record from all collections? Original images, canvas nodes and saved analysis evidence are retained.',
  'research.confirmDelete': 'Confirm deletion',
  'research.entry': 'Research record',
  'research.name': 'Name',
  'research.image': 'Existing project image',
  'research.noImage': 'Text or link only',
  'research.notes': 'Notes and observations',
  'research.source': 'Source URL (HTTP or HTTPS)',
  'research.tags': 'Tags (comma separated, up to 12)',
  'research.brand': 'Brand (user supplied)',
  'research.product': 'Product (user supplied)',
  'research.date': 'Recorded on (not release date)',
  'research.members': 'Choose records. The same record can belong to several collections.',
  'research.empty':
    'No research here yet. Add an image, link or note, then organize it into collections.',
  'research.edit': 'Edit research',
  'research.deleteEntry': 'Delete research record',
  'research.more': 'Show more research',
  'research.saved': 'Research saved locally.',
  'research.error':
    'Could not save or load research. Check the title, content, tags and HTTP(S) link. If another window changed the library, cancel editing and reload. Your draft is retained.',
  'materials.requestDetails': 'View full request',
  'materials.noSnapshots':
    'This older record has no saved image evidence. Current images are not substituted.',
  'materials.compare': 'Visual reference comparison',
  'materials.compareHint':
    'Select 2–8 images from this project below. Only these images and your question are sent to the selected model. This is not web research or verified market trends; review all conclusions.',
  'materials.selected': 'Selected evidence: {count}',
  'materials.question': 'Comparison question',
  'materials.runAnalysis': 'Confirm and analyze',
  'materials.history': 'Load saved analyses',
  'materials.selectCompare': 'Include in comparison',
  'materials.analysisError':
    'Comparison failed. Check image availability and the model’s vision support. No automatic retry was made.',
  'materials.noAnalysis':
    'No completed analysis. An interrupted run does not automatically resume.',
  'materials.hint':
    'Reuse saved images. Cross-project placement copies the file into this project; it does not create design lineage or run AI.',
  'materials.search': 'Search names, projects or reference notes',
  'materials.allProjects': 'Include other local projects',
  'materials.loading': 'Loading materials…',
  'materials.missing': 'Preview unavailable',
  'materials.error': 'Could not read local materials. Close and try again.',
  'materials.count': '{count} images',
  'materials.empty': 'No matching saved images. Import a reference or keep a candidate first.',
  'materials.place': 'Place on canvas',
  'materials.placed': 'Added an independent reference to this board.',
  'materials.placeError':
    'Could not place this material. Check that the file still exists and the workspace is saved.',
  'materials.more': 'Show more',
  'materials.edit': 'Edit knowledge',
  'materials.notes': 'Design notes',
  'materials.tags': 'Tags (comma-separated, up to 12)',
  'materials.source': 'Source URL',
  'materials.knowledgeHint':
    'Saved locally and included in project exports. Do not enter API keys, private credentials or secret links. Nothing is sent to a model.',
  'materials.invalid':
    'Use unique tags of up to 40 characters and an HTTP(S) URL without login details, or leave the URL empty.',
  'materials.save': 'Save knowledge',
  'materials.saved': 'Material knowledge saved.',
  'materials.saveError': 'Save failed. Your draft is still available; retry or cancel.',
  'materials.copyFirst': 'Place a copy in this project before editing its knowledge.',
  'common.create': 'Create',
  'common.delete': 'Delete',
  'common.discard': 'Discard',
  'common.done': 'Done',
  'common.error': 'Error',
  'common.loading': 'Loading…',
  'common.rename': 'Rename',
  'common.save': 'Save',
  'common.unknown': 'Unknown',
  'common.untitledProject': 'Untitled Project',
  'home.edition': 'Community Beta 0.1.0-beta.3 · Local-first',
  'generation.downloadImage': 'Download this image',
  'home.title': 'Start with the design intent.',
  'home.description':
    'Keep references, sketches, design lineage, materials, and 3D review in one local project.',
  'home.newProject': 'New Project',
  'home.openDemo': 'Open Demo Project',
  'home.openingDemo': 'Opening demo…',
  'home.openProject': 'Open Project',
  'graph.lineage': 'Variant lineage',
  'graph.relation.derived_from': 'Derived from',
  'graph.relation.references': 'References',
  'graph.relation.variant_of': 'Variant of',
  'graph.relation.same_design': 'Same design',
  'graph.relation.uses_cmf': 'Uses CMF',
  'graph.relation.generated_from': 'Generated from',
  'graph.relation.replaces': 'Replaces',
  'graph.relation.approved_from': 'Approved from',
  'graph.relation.generation_input': 'Generation input',
  'graph.relation.generation_output': 'Generation output',
  'graph.relation.related_to': 'Related to',
  'home.recentProjects': 'Recent Projects',
  'home.savedLocally': 'Projects are saved to this browser automatically.',
  'home.loadingProjects': 'Loading local projects…',
  'home.emptyTitle': 'No projects yet',
  'home.emptyDescription':
    'Create a blank project, or open the demo to see an industrial-design workflow.',
  'home.demoWorkspace': 'Demo workspace',
  'home.updated': 'Updated {date}',
  'home.boards': '{count} Board',
  'home.boardsPlural': '{count} Boards',
  'home.footerWorkspaces': 'Canvas · Graph · Sketch · 3D',
  'home.footerAutosave': 'Autosave on · Portable backups use .oidproj',
  'workspace.home': 'Home',
  'workspace.localProject': '{count} Boards · local project',
  'workspace.boards': 'Boards',
  'workspace.newBoard': 'New Board',
  'workspace.boardHint':
    'Boards separate exploration themes without breaking the project’s Design lineage.',
  'workspace.canvas': 'Canvas',
  'workspace.graph': 'Graph',
  'workspace.sketch': 'Sketch',
  'workspace.threeD': '3D',
  'workspace.ai': 'AI',
  'workspace.project': 'Project',
  'workspace.export': 'Export .oidproj',
  'workspace.import': 'Import .oidproj',
  'workspace.providerSettings': 'Provider Settings',
  'workspace.commands': 'Commands',
  'workspace.importReference': 'Import Reference',
  'workspace.newConcept': 'New Concept',
  'workspace.historyFailed':
    'Could not restore this operation. The board may have changed; current content has been preserved.',
  'workspace.newGeneration': 'New generation',
  'workspace.undo': 'Undo',
  'workspace.redo': 'Redo',
  'workspace.lineageDerived': 'Design lineage is derived from Design records.',
  'workspace.select': 'Select',
  'workspace.hand': 'Hand',
  'workspace.panShortcut': 'Hold Space and drag, or drag with the middle mouse button to pan.',
  'workspace.focusCanvas': 'Focus canvas',
  'workspace.exitFocus': 'Show panels',
  'workspace.moreTools': 'More tools',
  'workspace.lessTools': 'Fewer tools',
  'canvas.navigation': 'Canvas navigation',
  'generation.queue.order': 'Execution order',
  'generation.queue.noInputs': 'No images connected',
  'generation.queue.textInput': 'Text-only task',
  'generation.queue.missingInput': 'Source unavailable',
  'generation.queue.orderHint':
    'Tasks run from top to bottom. Reorder before confirming; failure stops the remaining tasks. To run again, close and reopen the queue and select tasks explicitly.',
  'generation.queue.up': 'Move {name} up',
  'generation.queue.down': 'Move {name} down',
  'canvas.help.title': 'Canvas help',
  'canvas.help.scope':
    'These controls apply to the main Canvas. Sketch, Graph and 3D have their own controls.',
  'canvas.help.select': 'Select and move',
  'canvas.help.selectHint':
    'Click a card to select it; drag to move it. Shift-click adds or removes a card from the selection.',
  'canvas.help.pan': 'Pan',
  'canvas.help.panHint':
    'Hold Space and drag, or use the middle mouse button to pan without switching tools.',
  'canvas.help.connect': 'Connect inputs',
  'canvas.help.connectHint':
    'Drag the right output port to a generation card’s left main/reference port. Escape cancels an unfinished connection.',
  'canvas.help.zoom': 'Navigate',
  'canvas.help.zoomHint':
    'Use the mouse wheel or − / + to zoom. Click the percentage for 100%, or Fit all to locate your work.',
  'canvas.help.undo': 'Undo / redo',
  'canvas.help.undoHint':
    'Ctrl/Cmd + Z / Ctrl/Cmd + Shift + Z. AI requests and candidate acceptance/discard are not ordinary layout undo.',
  'canvas.help.duplicate': 'Duplicate',
  'canvas.help.duplicateHint':
    'Ctrl/Cmd + D duplicates eligible selected cards. Review candidates before duplicating them.',
  'canvas.help.delete': 'Delete',
  'canvas.help.deleteHint':
    'Delete or Backspace removes eligible selected cards. Discard a candidate from its review controls; referenced results are protected.',
  'canvas.help.safety':
    'Canvas shortcuts do not operate while editing text or using a dialog. Editing or connecting never starts generation automatically.',
  'canvas.minimap': 'Overview map',
  'generation.compareGrid': 'Compare all results',
  'prompt.title': 'My prompt library',
  'prompt.hint':
    'Stored on this device, outside project exports. Saves only direction and notes, not model settings. Applying never generates automatically. Do not include secrets in prompts.',
  'prompt.name': 'Preset name',
  'prompt.save': 'Save current prompt',
  'prompt.search': 'Search presets',
  'prompt.reload': 'Reload library',
  'prompt.empty': 'No saved prompts yet.',
  'prompt.apply': 'Apply direction and notes',
  'prompt.delete': 'Delete preset',
  'prompt.confirm': 'Delete this preset? Existing generation steps are unchanged.',
  'prompt.confirmDelete': 'Confirm deletion',
  'prompt.cancel': 'Cancel',
  'prompt.saved': 'Prompt saved locally.',
  'prompt.applied': 'Prompt applied. Review settings and generate manually.',
  'prompt.deleted': 'Preset deleted.',
  'prompt.error':
    'Unable to read or save the library. Check storage permissions, available space and the 100-preset limit. Existing data has not been reset.',
  'canvas.locateNode': 'Locate card',
  'canvas.zoomOut': 'Zoom out',
  'canvas.zoomIn': 'Zoom in',
  'canvas.resetZoom': 'Reset zoom to 100%',
  'canvas.fitAll': 'Fit all',
  'workspace.text': 'Text',
  'image.importFailed':
    'Image import failed. Choose a valid PNG, JPEG, WebP, GIF or AVIF up to 25 MB and 32 megapixels. Existing content is preserved; if storage is full, back up your project before freeing space.',
  'text.default': 'Record a design observation here.',
  'text.content': 'Note content',
  'text.fontSize': 'Font size',
  'text.save': 'Save note',
  'text.failed': 'Could not save the note. Your draft is preserved.',
  'text.hint': 'Local canvas annotation; it is not sent as an AI prompt.',
  'workspace.image': 'Image',
  'workspace.toolUnavailable': 'Not available yet',
  'workspace.duplicate': 'Duplicate',
  'workspace.group': 'Group',
  'workspace.groupName': 'Group name',
  'workspace.copyCandidateHint': 'Adopt pending results before duplicating them or their group.',
  'workspace.ungroup': 'Ungroup',
  'workspace.groupHint':
    'Shift-select two or more unlocked, ungrouped cards. Drag the group header to move together; individual cards remain editable.',
  'workspace.localFirst': 'Local-first workspace',
  'workspace.designCount': '{count} Designs',
  'workspace.nodeCount': '{count} Nodes',
  'workspace.graphRuntime': 'Design graph view',
  'workspace.viewerRuntime': '3D review runtime',
  'workspace.canvasRuntime': 'Canvas runtime',
  'workspace.flush': 'Ctrl/Cmd + S flushes local changes',
  'workspace.loadingGraph': 'Loading Design Graph…',
  'workspace.loadingSketch': 'Loading Sketch Workspace…',
  'workspace.loadingViewer': 'Loading 3D Viewer…',
  'design.kind.concept': 'Concept',
  'design.kind.variant': 'Variant',
  'design.status.exploring': 'Exploring',
  'design.status.candidate': 'Candidate',
  'design.status.review': 'In review',
  'design.status.approved': 'Approved',
  'design.status.rejected': 'Rejected',
  'design.status.archived': 'Archived',
  'save.saving': 'Saving…',
  'save.saved': 'Saved',
  'save.failed': 'Save failed',
  'save.failedPreserved':
    'Save failed. Current edits are not saved. Retry before closing or refreshing. Previously saved data was not changed. {error}',
  'save.retry': 'Retry save',
  'archive.error.conflict':
    'This file conflicts with another local project. Nothing was replaced. Export a separate copy from the source project and try again.',
  'archive.error.tooLarge':
    'The file or unpacked content exceeds the safety limit. Export a smaller project and try again.',
  'archive.error.corrupt':
    'The file is damaged or is not an .oidproj archive. Download or export a complete copy again.',
  'archive.error.path':
    'The archive contains an unsafe file path. Use a project exported by this app.',
  'archive.error.manifest':
    'Project format information is missing or invalid. Export a new copy from the source app.',
  'archive.error.version':
    'This project version is not supported. Open it with a compatible app version; do not manually change its version number.',
  'archive.error.data':
    'Project data or relationships are incomplete. Restore a known good backup or export the source project again.',
  'archive.error.missingAsset':
    'The archive is missing images or other resource files. Export a complete project with its local resources.',
  'archive.error.storage':
    'The archive uses an unsupported resource storage type. Export a copy containing local resources.',
  'archive.error.secrets':
    'The archive contains credential fields. Remove credentials in the source app and export a safe copy.',
  'archive.error.unknown':
    'The operation could not be completed. Keep this page open, check local storage availability and try again.',
  'dialog.projectName': 'Project name',
  'dialog.boardName': 'Board name',
  'dialog.conceptName': 'Concept name',
  'dialog.nameNew': 'Name the new {item}',
  'dialog.rename': 'Rename {item}',
  'dialog.project': 'Project',
  'dialog.board': 'Board',
  'dialog.concept': 'Concept',
  'dialog.projectDescription':
    'A Project groups Boards, assets, Design lineage, and local backups.',
  'dialog.boardDescription': 'A Board is a focused workspace inside this Project.',
  'dialog.conceptDescription':
    'A Concept captures a deliberate industrial-design direction before variants are explored.',
  'dialog.saveName': 'Save name',
  'inspector.title': 'Inspector',
  'inspector.selection': 'Selection',
  'inspector.lineage': 'Design lineage',
  'inspector.review3d': '3D review',
  'inspector.noneTitle': 'Nothing selected',
  'inspector.noneDescription':
    'Select a card to inspect its design intent, assets, and available actions.',
  'inspector.basic': 'Basic information',
  'inspector.type': 'Type',
  'inspector.position': 'Position',
  'inspector.size': 'Size',
  'inspector.design': 'Design',
  'inspector.kind': 'Kind',
  'inspector.decision': 'Decision state',
  'inspector.lineageField': 'Lineage',
  'inspector.variantOf': 'Variant of {name}',
  'inspector.missingParent': 'unavailable source design',
  'inspector.approved': 'Approved Design',
  'inspector.readyCad': 'Ready for CAD',
  'inspector.dna': 'Design DNA',
  'dna.hint':
    'Choose what to preserve in future explorations. Saving does not generate images or change existing variants. These are model instructions, not guaranteed geometry locks.',
  'dna.silhouetteLocked': 'Preserve silhouette',
  'dna.proportionLocked': 'Preserve proportions',
  'dna.geometryLocked': 'Preserve primary structure',
  'dna.detailLocked': 'Preserve characteristic details',
  'dna.cmfLocked': 'Preserve color, material and finish',
  'dna.brandLocked': 'Preserve brand cues',
  'dna.notes': 'Additional constraints (one per line)',
  'dna.save': 'Save constraints',
  'dna.saved': 'Constraints saved. Existing results may now be based on old inputs.',
  'dna.failed': 'Could not save constraints. Your draft is kept; please try again.',
  'dna.limit': 'Use at most 40 lines and 4,000 characters.',
  'inspector.locked': 'Locked',
  'inspector.open': 'Open',
  'inspector.aiActions': 'AI actions',
  'inspector.aiDescription': 'Analysis and generation always preserve the selected source Design.',
  'inspector.openAi': 'Open AI actions',
  'inspector.cmf': 'CMF',
  'inspector.cmfDescription':
    'Material and finish are attached to the selected Design, not this Canvas card.',
  'inspector.view3d': 'View / 3D',
  'inspector.preview': 'Preview',
  'inspector.captured': 'Captured',
  'inspector.noCapture': 'No capture yet',
  'inspector.view': 'View',
  'inspector.model': 'Model',
  'candidate.title': 'Candidate Tray',
  'candidate.description':
    'Generated candidates remain here until you explicitly keep one as a Variant.',
  'candidate.loading': 'Generating candidates…',
  'candidate.empty': 'No candidates to review.',
  'candidate.previewUnavailable': 'Candidate preview unavailable',
  'candidate.keep': 'Keep as Variant',
  'provider.title': 'AI Provider Settings',
  'provider.description': 'OpenAI-compatible text, vision, and image generation with your own key.',
  'provider.add': 'Add Provider',
  'provider.name': 'Name',
  'provider.baseUrl': 'Base URL',
  'provider.model': 'Model ID',
  'provider.apiKey': 'API Key',
  'provider.keepKey': 'Leave blank to retain the existing key.',
  'provider.pasteKey': 'Paste your API key',
  'provider.remember': 'Remember this key locally on this browser',
  'provider.privacy':
    'Session-only keys disappear when this page closes. Remembered keys stay only in local browser storage and never enter project files.',
  'provider.save': 'Save Provider',
  'provider.test': 'Test Connection',
  'provider.keyChecking': 'Checking local credentials…',
  'provider.keyAvailable': 'A local key is available. You can test without entering it again.',
  'provider.testKeyRequired': 'Enter an API Key to test. No local key is currently available.',
  'provider.delete': 'Delete Provider',
  'provider.defaultName': 'OpenAI-compatible Provider',
  'ai.title': 'AI Workbench',
  'ai.sourceDesign': 'Source Design',
  'ai.manageProvider': 'Settings',
  'ai.description':
    'Only the selected Design and this prompt are sent to the chosen Provider. AI never overwrites the source Design.',
  'ai.provider': 'Provider',
  'ai.chooseProvider': 'Choose a Provider',
  'ai.notConfigured':
    'Provider not configured. Open Provider Settings to add your own OpenAI-compatible key.',
  'ai.checking': 'Checking local Provider key…',
  'ai.missingKey':
    'API Key missing for this Provider. Add one in Provider Settings before running AI actions.',
  'ai.prompt': 'Prompt or designer notes',
  'ai.selectDesign': 'Select a Design card before using an AI action.',
  'ai.selectedDesign': 'Selected Design: {name}',
  'ai.analyzing': 'Analyzing…',
  'ai.analyze': 'Analyze Design',
  'ai.generating': 'Generating…',
  'ai.generate': 'Generate Variant',
  'ai.renderUnavailable':
    'Render Sketch is unavailable until a configured Provider declares image-edit capability.',
  'ai.latestAnalysis': 'Latest analysis',
  'ai.defaultPrompt': 'Explore a refined portable lamp direction.',
  'feedback.unknownStorage': 'Unknown storage error.',
  'feedback.unknown': 'Unknown error.',
  'feedback.boardRequired': 'A project needs at least one Board.',
  'feedback.deleteProjectConfirm': 'Delete “{name}” and all of its local assets?',
  'feedback.deleteBoardConfirm': 'Delete Board “{name}” and its Canvas nodes?',
  'feedback.referenceImportFailed': 'Could not import reference.',
  'feedback.demoUnavailable':
    'The demo images could not be loaded. Please try opening the demo again.',
  'feedback.exported': 'Project backup is ready. Check your browser downloads.',
  'feedback.downloadBackup': 'Download backup again',
  'feedback.exportFailed': 'Export failed: {error}',
  'feedback.imported': 'Project imported and restored.',
  'feedback.importFailed': 'Import failed: {error}',
  'feedback.providerSaved': 'Provider settings saved.',
  'feedback.providerSaveFailed': 'Could not save Provider: {error}',
  'feedback.connecting': 'Connecting…',
  'feedback.connectionVerified': 'Connection verified.',
  'feedback.connectionFailed': 'Connection test failed: {error}',
  'feedback.providerDeleted': 'Provider deleted.',
  'feedback.designProviderRequired': 'Select a Design and configure a Provider first.',
  'feedback.analysisCompleted': 'Design analysis completed.',
  'feedback.analysisFailed': 'Design analysis failed.',
  'feedback.candidateGenerated':
    'Candidate generated. Review it in the Candidate Tray before keeping it.',
  'feedback.variantFailed': 'Variant generation failed.',
  'feedback.variantCreated': 'New Variant created from the selected candidate.',
  'feedback.candidateKeepFailed': 'Could not keep generated candidate.',
  'feedback.modelMissing': 'The selected model file is missing from local storage.',
  'feedback.modelOpenFailed': 'Could not open 3D model: {error}',
  'feedback.modelImportFailed': 'Model import failed: {error}',
  'feedback.viewerSaveFailed': 'Could not save viewer state: {error}',
  'feedback.captureSaved': 'Preview captured and saved locally as an image Asset.',
  'feedback.captureFailed': 'Could not save capture: {error}',
  'feedback.deleteProviderConfirm': 'Delete Provider “{name}” and its locally remembered key?',
  'feedback.storageUnavailable':
    'Local storage is unavailable. Existing data was not changed. Check IndexedDB/site storage, then reload. ({error})',
  'feedback.storageProjectsUnavailable':
    'Local storage is unavailable. Projects could not be loaded. Check IndexedDB/site storage, then reload. ({error})',
  'action.failed': 'Action failed.',
  'action.empty': 'No actions are available for this selection.',
  'action.palette': 'Command palette',
  'action.commands': 'Commands',
  'action.search': 'Search available actions',
  'action.selection': 'Selection actions',
  'action.workspace.duplicate.label': 'Duplicate selection',
  'action.workspace.duplicate.description': 'Create offset copies of the selected Canvas nodes.',
  'action.workspace.delete.label': 'Delete selection',
  'action.workspace.delete.description': 'Remove the selected Canvas nodes.',
  'action.design.variant.label': 'Create Variant',
  'action.design.variant.description':
    'Create a child Design and its board representation from a selected Design.',
  'action.ai.text.label': 'Generate text',
  'action.ai.text.description':
    'Generate text through the configured model-neutral capability router.',
  'action.ai.test.label': 'Test Provider connection',
  'action.ai.test.description':
    'Verify the configured Provider and API key without changing project data.',
  'action.ai.analyze.label': 'Analyze Design',
  'action.ai.analyze.description':
    'Ask the configured AI to analyze a selected Design without modifying it.',
  'action.ai.variant.label': 'Generate Variant',
  'action.ai.variant.description':
    'Generate candidates for a new Variant without changing the source Design.',
  'action.ai.keep.label': 'Keep generated candidate',
  'action.ai.keep.description': 'Create a new Variant from a selected AI candidate.',
  'sketch.workspace': 'Sketch workspace',
  'sketch.subtitle': 'Draw and refine an idea',
  'dialog.saveFailed': 'Could not save. Your input is still here; please try again.',
  'sketch.saveFailed': 'Could not save this sketch. Your drawing is still open; try again.',
  'sketch.edit': 'Edit original sketch',
  'sketch.staticHint':
    'This is a static sketch reference, not an editable drawing. You can use it as a generation input. To draw, choose Sketch in the top toolbar to create an editable sketch.',
  'sketch.sharedHint':
    'Copies of this sketch card share the original drawing. Saving updates their previews, not their positions or connections.',
  'sketch.loadFailed':
    'The editable sketch source is missing or invalid. The existing preview has not been changed.',
  'threeD.workspace': '3D workspace',
  'threeD.import': 'Import GLB / GLTF',
  'threeD.model': 'Model',
  'threeD.chooseModel': 'Choose a local model',
  'threeD.return': 'Return to Workspace',
  'threeD.title': '3D Viewer',
  'threeD.empty':
    'Import a GLB / GLTF model, or select a 3D card in the Workspace and open it here.',
  'threeD.camera': 'Camera',
  'threeD.perspective': 'Perspective',
  'threeD.orthographic': 'Orthographic',
  'threeD.presets': 'View presets',
  'threeD.front': 'Front',
  'threeD.side': 'Side',
  'threeD.rear': 'Rear',
  'threeD.top': 'Top',
  'threeD.fit': 'Fit to Object',
  'threeD.reset': 'Reset View',
  'threeD.grid': 'Grid',
  'threeD.ground': 'Ground',
  'threeD.wireframe': 'Wireframe',
  'threeD.capture': 'Capture View',
  'threeD.controls': 'Orbit: left drag · Pan: right drag · Zoom: wheel',
  'threeD.info': 'Model information',
  'threeD.file': 'File',
  'threeD.format': 'Format',
  'threeD.meshes': 'Meshes',
  'threeD.bounds': 'Bounds',
  'threeD.previewUnavailable': 'Model preview unavailable.',
  'threeD.loadFailed':
    'Could not load this model. Your file is still saved. Retry or choose another model.',
  'threeD.retry': 'Retry loading',
  'canvas.workspace': 'Workspace canvas',
  'canvas.emptyTitle': 'Start with a reference or an idea',
  'canvas.emptyDescription':
    'Import an image for inspiration, or create a concept to record your design intent. No AI connection is needed.',
  'canvas.emptyHint':
    'Then branch into design directions and compare results. AI only runs when you click Generate.',
  'canvas.derivedFrom': 'Derived from {name}',
  'canvas.derived': 'Derived design',
  'node.text': 'NOTE',
  'node.image': 'IMAGE',
  'node.reference': 'REFERENCE',
  'node.sketch': 'SKETCH',
  'node.concept': 'CONCEPT',
  'node.variant': 'VARIANT',
  'node.viewset': 'MULTI-VIEW',
  'node.cmf': 'CMF',
  'node.model3d': '3D REVIEW',
  'node.group': 'GROUP',
  'node.generation': 'GENERATE',
  'generation.direction': 'Design direction',
  'generation.tool.change': 'Change task',
  'generation.batch.title': 'Batch exploration',
  'generation.queue.title': 'Run task queue',
  'generation.batch.references': 'Shared references (optional, up to 4)',
  'generation.batch.referencesHint':
    'Every task reads these connected images. A main image cannot also be a shared reference. No request is sent until you run a task.',
  'generation.queue.hint':
    'Choose up to 16 saved tasks in execution order. Validate task inputs before confirming. Failure stops the queue; completed results stay. Closing or refreshing never resumes requests automatically.',
  'generation.queue.tasks': 'Tasks to run',
  'generation.queue.summary': '{tasks} tasks · up to {images} results',
  'generation.queue.cost':
    'The selected Provider charges for generation. Cancellation may not stop billing for requests already sent. No automatic retries.',
  'generation.queue.run': 'Confirm and run queue',
  'generation.queue.running': 'Running',
  'generation.queue.success': 'Completed',
  'generation.queue.cancelled': 'Cancelled',
  'generation.queue.failed':
    'Queue stopped. Completed results were retained; check the failed task before manually starting a new queue.',
  'generation.queue.complete': 'All selected tasks completed. Review their results on the canvas.',
  'generation.batch.hint':
    'Prepare independent tasks for each main image × direction. This step only saves drafts; it does not call a model. Run tasks manually after reviewing their inputs.',
  'generation.batch.sources': 'Main images (1–4)',
  'generation.batch.sharedBrief': 'Shared design brief (optional)',
  'generation.batch.sharedBriefHint':
    'For a product family, describe shared form, materials and detail language here; use directions for individual differences. Copied into each task when prepared, not linked afterward. Model consistency still needs review.',
  'generation.batch.briefLimit':
    'Shared brief plus each direction must not exceed 10,000 characters. Shorten the brief or direction.',
  'generation.batch.directions': 'Design directions (1–4)',
  'generation.batch.name': 'Direction {number} name',
  'generation.batch.remove': 'Remove direction',
  'generation.batch.add': 'Add direction',
  'generation.batch.count': 'Results per task',
  'generation.batch.summary':
    '{tasks} tasks · {images} planned images. No generation request when preparing.',
  'generation.batch.prepare': 'Prepare tasks on canvas',
  'generation.batch.failed':
    'Could not save the batch. No partial tasks were kept. Check inputs and local storage, then try again.',
  'generation.tool.custom': 'Custom task',
  'generation.tool.patternCreate': 'Pattern artwork',
  'generation.tool.patternCreateHint':
    'Create flat artwork from text or connected references. Tile mode requests repeatable edges; inspect seams yourself.',
  'generation.prompt.patternCreate':
    'Create flat decorative artwork. Describe motifs, colors and visual style.',
  'generation.tool.patternTransfer': 'Pattern transfer',
  'generation.tool.patternTransferHint':
    'Connect one product main image and one pattern reference. AI interprets placement and scale; use flat placement for exact positioning.',
  'generation.prompt.patternTransfer':
    'Apply the reference artwork to the product, preserving its identity and functional structure.',
  'generation.patternTask.input': 'Artwork input',
  'generation.patternTask.text': 'Text only',
  'generation.patternTask.images': 'Connected image references',
  'generation.patternTask.repeat': 'Artwork layout',
  'generation.patternTask.single': 'Standalone motif',
  'generation.patternTask.tile': 'Repeatable tile (inspect seams)',
  'generation.patternTask.placement': 'Target part / placement',
  'generation.patternTask.scale': 'Relative motif scale',
  'generation.patternTask.small': 'Small',
  'generation.patternTask.medium': 'Medium',
  'generation.patternTask.large': 'Large',
  'generation.patternTask.required':
    'Connect exactly one product main image and one pattern reference, and specify the target part. These are AI instructions, not guaranteed surface mapping.',
  'generation.tool.localCmf': 'Local CMF',
  'generation.tool.localCmfHint':
    'Select a part, specify its color, material or finish, and preserve pixels outside the selection.',
  'generation.prompt.localCmf':
    'Change only the selected part CMF while preserving the product geometry and functional details.',
  'generation.localCmf.color': 'Target color',
  'generation.localCmf.material': 'Target material',
  'generation.localCmf.finish': 'Target surface finish',
  'generation.localCmf.fieldsHint':
    'Specify at least one attribute. Leave other fields blank to preserve them. Model fidelity still requires review.',
  'generation.tool.text': 'Text to concept',
  'generation.tool.textHint':
    'Start from words without input images. Results become independent candidates; no source design is required.',
  'generation.prompt.text':
    'Design a product concept. Describe its function, form, materials and intended context.',
  'generation.text.disconnect':
    'To start from text only, explicitly disconnect the input images first. Existing images are never silently ignored.',
  'generation.intent': 'Exploration intent',
  'generation.tool.label': 'Design tool',
  'generation.tool.view': 'Explore a view',
  'generation.tool.viewHint':
    'Connect the product as the main image. Select up to four views. Each view is generated separately from the same inputs; geometry consistency still depends on the model.',
  'generation.view.batch':
    'Will send {count} image-edit requests, one per selected view. Provider charges apply to each request. No automatic retries; results are saved only if all views succeed.',
  'generation.prompt.view':
    'Visualize the same product from a different camera view. Preserve its form, proportions, details and CMF. Use a neutral studio background.',
  'generation.view.label': 'Requested view',
  'provider.supportsMask': 'This service and model support image-edit masks',
  'provider.maskHint':
    'Enable only after checking your service documentation. Connection testing does not verify mask support.',
  'generation.tool.local': 'Local edit',
  'generation.tool.erase': 'Object eraser',
  'generation.tool.cutout': 'Remove background',
  'generation.tool.pattern': 'Place pattern',
  'generation.tool.patternHint':
    'Position an image or transparent pattern precisely. Local flat compositing, not automatic curved-surface mapping.',
  'generation.prompt.pattern': 'Place the reference pattern on the main product image.',
  'generation.pattern.help':
    'Drag in the preview to position the pattern center. Adjust size, rotation and opacity below. Transparent PNG patterns work best.',
  'generation.pattern.inputs': 'Connect one main image and one pattern reference.',
  'generation.pattern.local':
    'Local compositing only. No API key, model request or provider charge.',
  'generation.pattern.run': 'Create composite candidate',
  'generation.pattern.x': 'Horizontal center (%)',
  'generation.pattern.y': 'Vertical center (%)',
  'generation.pattern.width': 'Width (%)',
  'generation.pattern.height': 'Height (%)',
  'generation.pattern.rotation': 'Rotation (°)',
  'generation.pattern.opacity': 'Opacity (%)',
  'generation.tool.cutoutHint':
    'Keep the source product colors and use the returned alpha mask. Opaque, empty or differently sized results are rejected. Review the boundary before adopting.',
  'generation.prompt.cutout':
    'Remove the background, preserving the complete product and its original position and dimensions.',
  'generation.cutout.required':
    'Connect only one main image and confirm transparent PNG support in Provider settings.',
  'provider.supportsTransparency': 'This service and model support transparent PNG editing output',
  'generation.tool.eraseHint':
    'Select the object to remove. Sends a real mask and protects pixels outside the selection. Background reconstruction depends on the model; review the candidate before adopting.',
  'generation.prompt.erase':
    'Remove the selected object or detail and reconstruct the surrounding surface or background naturally. Do not insert a replacement object.',
  'generation.tool.localHint':
    'Select a rectangle on the main image, then describe the change. A real alpha mask is sent. Only the selected pixels are composited into the source; mismatched dimensions are rejected. Quality inside the selection depends on the model.',
  'generation.prompt.local':
    'Modify the selected area of the main product according to the following instructions. Preserve the structure, materials, lighting and background outside the area.',
  'generation.mask.title': 'Edit selection',
  'generation.mask.tool': 'Selection tool',
  'generation.mask.rectangle': 'Rectangle',
  'generation.mask.polygon': 'Polygon',
  'generation.mask.brush': 'Brush',
  'generation.mask.diameter': 'Brush diameter (short image side)',
  'generation.mask.polygonHelp':
    'Click along the outline, then finish the selection. Escape cancels unfinished points.',
  'generation.mask.finish': 'Finish selection',
  'generation.mask.undoPoint': 'Undo point',
  'generation.mask.undoStroke': 'Undo last stroke',
  'generation.mask.limit': 'Selection limit reached. Undo a stroke or simplify the outline.',
  'generation.mask.protectionFailed':
    'Local edit could not be safely merged: the returned image is unreadable or its dimensions differ from the source. No candidate was saved; no automatic retry was sent.',
  'generation.compareMode': 'Comparison mode',
  'generation.compareSource': 'Source comparison',
  'generation.compareCandidates': 'Compare candidates',
  'generation.compareWith': 'Compare with',
  'generation.reviewTarget': 'Actions apply to: {name}',
  'generation.mask.loading': 'Loading source image…',
  'generation.mask.precision': 'Adjust selection precisely',
  'generation.mask.x': 'Left (%)',
  'generation.mask.y': 'Top (%)',
  'generation.mask.width': 'Width (%)',
  'generation.mask.height': 'Height (%)',
  'generation.mask.help':
    'Select the part with a rectangle, polygon or brush. Only the blue area is merged into the result; source pixels outside it are retained. Leave room for the part edges.',
  'generation.mask.selected': 'Selection saved. Changing the main source requires a new selection.',
  'generation.mask.clear': 'Clear selection',
  'generation.mask.mainRequired': 'Connect a main image with a preview before selecting an area.',
  'generation.mask.providerRequired':
    'Confirm mask support for the selected model in Provider settings before generating.',
  'generation.view.request':
    'Requested camera view: {view}. Return a single product view per image, not a contact sheet. All requested candidates are alternatives of this camera view. Preserve product identity, geometry and CMF; do not invent a different product.',
  'generation.view.front': 'Front',
  'generation.view.side': 'Side',
  'generation.view.rear': 'Rear',
  'generation.view.top': 'Top',
  'generation.view.perspective': 'Perspective',
  'generation.tool.choose': 'Choose a task brief…',
  'generation.tool.limit':
    'Model quality and consistency vary. Local editing and erasing use a real selection mask; other directions are editable briefs. Choosing a tool replaces the direction below without sending a request.',
  'generation.tool.sketch': 'Render a sketch',
  'generation.tool.lineart': 'Extract product linework',
  'generation.tool.lineartHint':
    'Use the product image as the main input. Generate editable-direction raster linework; not vector tracing or CAD geometry.',
  'generation.prompt.lineart':
    'Extract clean industrial-design linework from the main product image. Preserve its silhouette, proportions, camera view, part boundaries and functional details. Use controlled dark contour lines on a plain white background; remove material color, texture, reflections, cast shadows and scene clutter. Do not redesign the product, invent hidden geometry, add labels, dimensions or extra views. Additional references may guide line weight only, not replace the main product. Return a single raster line drawing suitable as a sketch reference, not a CAD or vector file.',
  'generation.tool.sketchHint':
    'Connect a sketch as the main image; add material or rendering references.',
  'generation.tool.blend': 'Blend form language',
  'generation.tool.blendHint': 'Use the product as the main image and another form as a reference.',
  'generation.tool.style': 'Transfer design language',
  'generation.tool.styleHint':
    'Preserve the product identity; connect a reference for its visual language.',
  'generation.tool.formHint':
    'Explore alternative silhouettes without losing the functional intent.',
  'generation.tool.cmfHint':
    'Keep the structure and explore material, color and finish references.',
  'generation.tool.sceneHint':
    'Keep the product identity and describe a plausible use environment.',
  'generation.prompt.sketch':
    'Translate the main sketch into an industrial design visualization. Preserve its silhouette, proportions and functional structure. Use references only for materials, lighting and rendering treatment; do not replace the sketch with the reference product.',
  'generation.prompt.blend':
    'Preserve the main product function and key proportions. Combine selected form characteristics from the references into a coherent new design, not a collage. Maintain plausible construction and distinguish the new direction from the source.',
  'generation.prompt.style':
    'Preserve the main product identity, function and proportions. Interpret the connected references as design-language guidance for surfaces, details and transitions, without copying their branding or replacing the product.',
  'generation.setup': 'Run settings',
  'generation.review': 'Review before keeping. The source design remains unchanged.',
  'generation.mask.protectionHint':
    'Pixels outside the selected area are preserved. The model may still alter structure inside it; use a tight selection with room around the part.',
  'generation.mask.reviewHint':
    'Request completed does not mean the edit is correct. Check the part shape, material and boundary seams against the source before keeping.',
  'generation.presets': 'Direction starters · editable, no automatic generation',
  'generation.preset.form': 'Explore form',
  'generation.preset.cmf': 'Explore CMF',
  'generation.preset.scene': 'Explore a setting',
  'generation.prompt.form':
    'Preserve the product function and key proportions. Explore a distinct, coherent form language using the connected references.',
  'generation.prompt.cmf':
    'Preserve the product silhouette and structure. Explore a coherent material, color and finish direction using the connected references.',
  'generation.prompt.scene':
    'Preserve the product identity and proportions. Present it in a plausible use setting with coherent lighting and scale.',
  'generation.viewCandidate': 'View candidate',
  'generation.compare': 'Review candidates',
  'generation.source': 'Current main input',
  'generation.candidateNumber': 'Candidate {number}',
  'generation.disconnect': 'Disconnect {name}',
  'generation.discardReferenced':
    'This result is used by a later step. Disconnect its downstream inputs before discarding it.',
  'generation.notes': 'Additional guidance',
  'generation.count': 'Results',
  'generation.run': 'Generate',
  'generation.configure': 'Configure model',
  'generation.cardProvider': 'Model: {name} · {count} images',
  'generation.cardProviderMissing': 'Model not configured',
  'generation.running': 'Generating…',
  'generation.cancel': 'Cancel generation',
  'generation.cancelled':
    'Generation cancelled. The service may still charge for work already started.',
  'generation.ready': 'Ready to generate',
  'generation.stale': 'Inputs changed since these results',
  'generation.failed': 'Generation failed',
  'generation.providerRequired': 'Configure an image-edit Provider and API key first.',
  'generation.noInputs': 'Connect at least one image, sketch, Concept, or Variant.',
  'generation.billing': 'Your Provider may charge for each generated image.',
  'generation.selectSource':
    'Drag from the right edge of a visual card to the main or reference input.',
  'generation.base': 'Main image',
  'generation.reference': 'Reference',
  'generation.connected': '{count} images connected',
  'generation.candidates': 'Candidates',
  'generation.selectedOnCanvas': 'Selected on canvas',
  'generation.resultSelection': 'Candidate result',
  'generation.openStep': 'View generation step',
  'generation.continueExploration': 'Continue exploration',
  'generation.moreTools': 'More image tools',
  'generation.manualStepHint':
    'Choose an operation. This image is connected automatically; generation starts only when you click Generate.',
  'generation.stepSource': 'Source step and instruction',
  'generation.keepDesign': 'Keep as design',
  'generation.keepReference': 'Save as reference',
  'generation.previewUnavailable': 'Candidate preview unavailable',
  'generation.generatedConceptName': 'Generated Concept',
  'generation.generatedVariantName': '{name} Variant',
  'generation.generatedReferenceName': 'Generated reference',
} as const;

export type MessageKey = keyof typeof englishMessages;

const simplifiedChineseMessages: Record<MessageKey, string> = {
  'views.title': '视图集',
  'decision.next': '更改决策状态',
  'decision.save': '保存设计决策',
  'decision.hint': '仅记录设计师的本地决策，不代表已通过工程制造验证，也不调用 AI。',
  'decision.failed': '保存失败，方案可能已发生变化，请重新选中后重试。',
  'decision.archiveConfirm':
    '确认归档此方案？当前版本的归档是终止状态，不能再切换状态；不会删除图片、子方案或画布卡片。',
  'decision.archived': '已归档。当前版本不重新打开归档决策；方案和图片仍然保留。',
  'design.createVariant': '手动创建变体',
  'design.createConcept': '以此图建立概念方案',
  'design.conceptName': '概念方案名称',
  'design.manualConceptHint':
    '复用参考图或已保存草图预览建立方案，保留原素材卡；不调用 AI，也不代表获得原图版权。',
  'design.conceptFailed': '概念方案创建失败，请检查图片或已保存草图预览是否可用，再重试。',
  'design.variantName': '变体名称',
  'design.manualVariantHint':
    '复用当前预览图和设计约束创建子方案，不生成新图、不调用 AI，也不覆盖来源方案。',
  'design.variantFailed': '变体创建失败，名称已保留，请重试。',
  'cmf.title': 'CMF 方案集',
  'cmf.choose': '选择 CMF 方案集',
  'cmf.new': '新建 CMF 方案集',
  'cmf.name': '名称',
  'cmf.alternative': '配色材质方案',
  'cmf.material': '材质',
  'cmf.finish': '表面工艺',
  'cmf.notes': '备注',
  'cmf.colorName': '颜色名称',
  'cmf.hex': '颜色 HEX',
  'cmf.texture': '纹理参考图',
  'cmf.remove': '移除这套方案',
  'cmf.add': '添加配色材质方案',
  'cmf.save': '保存 CMF 方案集',
  'cmf.saved': 'CMF 方案集已保存。',
  'cmf.failed': 'CMF 保存失败，草稿已保留，请重试。',
  'cmf.hint':
    '仅保存本地设计记录，不渲染图片、不调用 AI。最多 24 套，画布预览前四套。纹理图用于参考，不代表已应用到 3D 材质。',
  'views.choose': '选择视图集',
  'views.new': '新建视图集',
  'views.place': '保存并放回当前画板',
  'views.name': '视图集名称',
  'views.hint':
    '分配当前画板中已保存的图片，仅本地保存，不调用 AI、不改变方案血缘。候选图请先采纳。',
  'views.empty': '未分配图片',
  'views.retained': '已保存图片',
  'views.front': '正面',
  'views.rear': '背面',
  'views.left': '左侧',
  'views.right': '右侧',
  'views.top': '顶部',
  'views.bottom': '底部',
  'views.perspective': '透视',
  'views.save': '保存视图集',
  'views.saved': '视图集已保存。',
  'views.failed': '保存失败，草稿已保留，请重试。',
  'language.label': '语言',
  'language.zh-CN': '简体中文',
  'language.en': 'English',
  'common.add': '添加',
  'common.cancel': '取消',
  'common.close': '关闭',
  'materials.title': '本地素材',
  'research.title': '收藏资料',
  'research.analyze': '分析所选资料',
  'research.selected': '已选资料：{count} 条',
  'research.analyzeHint':
    '选择 1–8 条资料，先核对图片和文字再发送。用户填写的信息未经核实，来源链接不会抓取。纯文字资料使用文字分析；包含图片时要求模型支持视觉。',
  'research.review': '核对所选依据',
  'research.sent': '将发送 {count} 条资料、{images} 张不同图片及你的问题。仅包含下方列出的资料。',
  'research.analysisError':
    '分析失败。请确认资料未被修改、图片可用且模型支持该输入。没有自动重试，也没有降级为纯文字分析。',
  'research.importImage': '导入图片到收藏',
  'research.importError':
    '图片导入失败。请选择可解码的 PNG、JPEG、WebP、GIF 或 AVIF，最大 25 MB、3200 万像素；若其他窗口修改了资料，请重新读取后再试。',
  'research.search': '搜索资料名称、标签、品牌或产品',
  'research.hint':
    '自行收集图片、链接与笔记，资料保存在本地并随工程导出。不自动抓取网页或调用 AI，请勿填写密钥和私密信息。',
  'research.addEntry': '添加资料',
  'research.addCollection': '新建收藏板',
  'research.reload': '重新读取已保存资料',
  'research.collection': '收藏板',
  'research.all': '全部资料',
  'research.editCollection': '编辑收藏板与成员',
  'research.deleteCollection': '删除收藏板',
  'research.deleteCollectionHint': '仅删除此收藏板？资料条目、原图与设计均会保留。',
  'research.deleteEntryHint':
    '从所有收藏板移除此资料记录？原图、画布节点和已保存的分析证据均会保留。',
  'research.confirmDelete': '确认删除',
  'research.entry': '资料记录',
  'research.name': '名称',
  'research.image': '工程中的已有图片',
  'research.noImage': '仅文字或链接',
  'research.notes': '笔记与观察',
  'research.source': '来源链接（HTTP 或 HTTPS）',
  'research.tags': '标签（逗号分隔，最多 12 个）',
  'research.brand': '品牌（用户填写）',
  'research.product': '产品（用户填写）',
  'research.date': '记录日期（不是发布日期）',
  'research.members': '选择资料，同一条资料可以加入多个收藏板。',
  'research.empty': '这里还没有资料。先添加图片、链接或笔记，再整理到收藏板中。',
  'research.edit': '编辑资料',
  'research.deleteEntry': '删除资料记录',
  'research.more': '显示更多资料',
  'research.saved': '资料已保存到本地。',
  'research.error':
    '资料读取或保存失败。请检查名称、内容、标签和 HTTP(S) 链接；若其他窗口已修改资料，请取消编辑后重新读取。当前草稿已保留。',
  'materials.requestDetails': '查看完整请求',
  'materials.noSnapshots': '此旧记录没有保存图片快照，不使用当前图片替代历史依据。',
  'materials.compare': '参考图片视觉对比',
  'materials.compareHint':
    '在下方选择当前项目的 2–8 张图片。只向所选模型发送这些图片及问题，不发送素材知识记录。这不是联网研究或已验证的市场趋势，结论需评审。',
  'materials.selected': '已选证据：{count} 张',
  'materials.question': '对比问题',
  'materials.runAnalysis': '确认并分析',
  'materials.history': '读取已保存分析',
  'materials.selectCompare': '加入对比',
  'materials.analysisError': '对比失败，请检查图片和模型的视觉能力。没有自动重试。',
  'materials.noAnalysis': '没有已完成的分析；中断记录不会自动续跑。',
  'materials.hint': '复用已保存图片。跨项目放置会复制文件到当前工程，不创建设计血缘，也不运行 AI。',
  'materials.search': '搜索图片名、项目或参考说明',
  'materials.allProjects': '包含其他本地项目',
  'materials.loading': '正在读取素材…',
  'materials.missing': '预览不可用',
  'materials.error': '无法读取本地素材，请关闭后重试。',
  'materials.count': '{count} 张图片',
  'materials.empty': '没有匹配的已保存图片，请先导入参考图或采纳候选。',
  'materials.place': '放到画布',
  'materials.placed': '已作为独立参考图加入当前画板。',
  'materials.placeError': '无法放置素材，请检查文件仍存在且工作区已保存。',
  'materials.more': '显示更多',
  'materials.edit': '编辑知识记录',
  'materials.notes': '设计说明',
  'materials.tags': '标签（逗号分隔，最多 12 个）',
  'materials.source': '来源链接',
  'materials.knowledgeHint':
    '保存在本机并随工程导出，请勿填写 API Key、账号密码或私密链接。不会发送给模型。',
  'materials.invalid':
    '标签不能重复，每个最多 40 字符；来源填写不含登录信息的 HTTP(S) 链接，或留空。',
  'materials.save': '保存知识记录',
  'materials.saved': '素材知识记录已保存。',
  'materials.saveError': '保存失败，草稿仍保留，可重试或取消。',
  'materials.copyFirst': '先放入当前工程，再编辑副本的知识记录。',
  'common.create': '创建',
  'common.delete': '删除',
  'common.discard': '丢弃',
  'common.done': '完成',
  'common.error': '错误',
  'common.loading': '加载中…',
  'common.rename': '重命名',
  'common.save': '保存',
  'common.unknown': '未知',
  'common.untitledProject': '未命名项目',
  'home.edition': '社区公测版 0.1.0-beta.3 · 本地优先',
  'generation.downloadImage': '下载此图片',
  'home.title': '从设计意图开始。',
  'home.description': '在一个本地项目中组织参考图、草图、设计血缘、材料和 3D 评审。',
  'home.newProject': '新建项目',
  'home.openDemo': '打开示例项目',
  'home.openingDemo': '正在打开示例…',
  'home.openProject': '打开项目',
  'graph.lineage': '方案派生',
  'graph.relation.derived_from': '派生自',
  'graph.relation.references': '参考关系',
  'graph.relation.variant_of': '方案变体',
  'graph.relation.same_design': '同一方案',
  'graph.relation.uses_cmf': '采用 CMF',
  'graph.relation.generated_from': '生成自',
  'graph.relation.replaces': '替代关系',
  'graph.relation.approved_from': '批准自',
  'graph.relation.generation_input': '生成输入',
  'graph.relation.generation_output': '生成输出',
  'graph.relation.related_to': '关联关系',
  'home.recentProjects': '最近项目',
  'home.savedLocally': '项目会自动保存在此浏览器中。',
  'home.loadingProjects': '正在加载本地项目…',
  'home.emptyTitle': '还没有项目',
  'home.emptyDescription': '创建空白项目，或打开示例项目了解工业设计工作流。',
  'home.demoWorkspace': '示例工作区',
  'home.updated': '更新于 {date}',
  'home.boards': '{count} 个画板',
  'home.boardsPlural': '{count} 个画板',
  'home.footerWorkspaces': '画布 · 图谱 · 草图 · 3D',
  'home.footerAutosave': '已开启自动保存 · 可使用 .oidproj 便携备份',
  'workspace.home': '主页',
  'workspace.localProject': '{count} 个画板 · 本地项目',
  'workspace.boards': '画板',
  'workspace.newBoard': '新建画板',
  'workspace.boardHint': '画板用于分隔探索主题，同时保持项目的设计血缘连续。',
  'workspace.canvas': '画布',
  'workspace.graph': '图谱',
  'workspace.sketch': '草图',
  'workspace.threeD': '3D',
  'workspace.ai': 'AI',
  'workspace.project': '项目',
  'workspace.export': '导出 .oidproj',
  'workspace.import': '导入 .oidproj',
  'workspace.providerSettings': '模型连接设置',
  'workspace.commands': '命令',
  'workspace.importReference': '导入参考图',
  'workspace.newConcept': '新建概念方案',
  'workspace.historyFailed': '未能恢复此操作，画板可能已发生变化；当前内容已保留。',
  'workspace.newGeneration': '新建生成节点',
  'workspace.undo': '撤销',
  'workspace.redo': '重做',
  'workspace.lineageDerived': '设计血缘由设计方案记录生成。',
  'workspace.select': '选择',
  'workspace.hand': '平移',
  'workspace.panShortcut': '按住空格拖动，或按住鼠标中键拖动，即可平移画布。',
  'workspace.focusCanvas': '专注画布',
  'workspace.exitFocus': '显示面板',
  'workspace.moreTools': '更多工具',
  'workspace.lessTools': '收起工具',
  'canvas.navigation': '画布导航',
  'generation.queue.order': '执行顺序',
  'generation.queue.noInputs': '尚未连接图片',
  'generation.queue.textInput': '纯文字任务',
  'generation.queue.missingInput': '来源不可用',
  'generation.queue.orderHint':
    '按下列顺序依次执行，确认前可调整；失败即停止后续任务。如需再次运行，请关闭并重新打开队列，明确选择要运行的任务。',
  'generation.queue.up': '上移 {name}',
  'generation.queue.down': '下移 {name}',
  'canvas.help.title': '操作帮助',
  'canvas.help.scope': '以下操作适用于主画布；草图、图谱和 3D 使用各自的操作方式。',
  'canvas.help.select': '选择与移动',
  'canvas.help.selectHint': '单击卡片选中，拖动卡片移动；按住 Shift 单击可加入或移出多选。',
  'canvas.help.pan': '平移画布',
  'canvas.help.panHint': '按住空格拖动，或按住鼠标中键拖动，无需切换工具即可平移画布。',
  'canvas.help.connect': '连接输入',
  'canvas.help.connectHint':
    '从卡片右侧输出端口拖到生成卡片左侧的主图／参考图端口。按 Esc 取消尚未完成的连线。',
  'canvas.help.zoom': '缩放与定位',
  'canvas.help.zoomHint': '滚轮或 −／+ 缩放；点击百分比恢复 100%，点击「查看全部」定位所有内容。',
  'canvas.help.undo': '撤销／重做',
  'canvas.help.undoHint':
    'Ctrl/Cmd + Z／Ctrl/Cmd + Shift + Z。模型请求、候选采纳和丢弃不属于普通布局撤销。',
  'canvas.help.duplicate': '复制卡片',
  'canvas.help.duplicateHint': 'Ctrl/Cmd + D 复制允许复制的选中卡片；待评审候选需先采纳再复制。',
  'canvas.help.delete': '删除卡片',
  'canvas.help.deleteHint':
    'Delete 或 Backspace 删除允许删除的选中卡片；候选从评审操作中丢弃，被引用的结果受到保护。',
  'canvas.help.safety': '编辑文字或打开弹窗时不会触发画布快捷键。编辑和连线不会自动发起生成请求。',
  'canvas.minimap': '小地图',
  'generation.compareGrid': '全部结果对比',
  'prompt.title': '我的提示词库',
  'prompt.hint':
    '保存在本机，不随工程导出。仅保存方向与说明，不保存模型设置；套用不会自动生成。请勿在提示词中填写密钥。',
  'prompt.name': '预设名称',
  'prompt.save': '保存当前提示词',
  'prompt.search': '搜索预设',
  'prompt.reload': '重新读取',
  'prompt.empty': '还没有保存的提示词。',
  'prompt.apply': '套用方向与说明',
  'prompt.delete': '删除预设',
  'prompt.confirm': '删除这个预设？已建立的生成步骤不受影响。',
  'prompt.confirmDelete': '确认删除',
  'prompt.cancel': '取消',
  'prompt.saved': '提示词已保存在本机。',
  'prompt.applied': '已套用，请检查参数后手动生成。',
  'prompt.deleted': '预设已删除。',
  'prompt.error':
    '无法读取或保存提示词库，请检查存储权限、可用空间和 100 条上限。原有数据未被重置。',
  'canvas.locateNode': '定位卡片',
  'canvas.zoomOut': '缩小画布',
  'canvas.zoomIn': '放大画布',
  'canvas.resetZoom': '恢复 100% 缩放',
  'canvas.fitAll': '查看全部',
  'workspace.text': '文本',
  'image.importFailed':
    '图片导入失败。请选择有效的 PNG、JPEG、WebP、GIF 或 AVIF，文件不超过 25 MB、3200 万像素。已有内容不会被替换；若存储已满，请先备份工程再清理空间。',
  'text.default': '在这里记录设计观察。',
  'text.content': '备注内容',
  'text.fontSize': '文字大小',
  'text.save': '保存备注',
  'text.failed': '备注保存失败，草稿已保留。',
  'text.hint': '本地画布备注，不会作为 AI 提示词发送。',
  'workspace.image': '图片',
  'workspace.toolUnavailable': '暂未开放',
  'workspace.duplicate': '复制',
  'workspace.group': '分组',
  'workspace.groupName': '分组名称',
  'workspace.copyCandidateHint': '请先采纳待评审结果，再复制它或所在分组。',
  'workspace.ungroup': '解组',
  'workspace.groupHint':
    '按住 Shift 选择至少两张未锁定、未分组卡片。拖动组标题整体移动，卡片仍可独立编辑。',
  'workspace.localFirst': '本地优先工作台',
  'workspace.designCount': '{count} 个方案',
  'workspace.nodeCount': '{count} 个节点',
  'workspace.graphRuntime': '设计图谱视图',
  'workspace.viewerRuntime': '3D 评审运行时',
  'workspace.canvasRuntime': '画布运行时',
  'workspace.flush': 'Ctrl/Cmd + S 立即写入本地更改',
  'workspace.loadingGraph': '正在加载设计图谱…',
  'workspace.loadingSketch': '正在加载草图工作区…',
  'workspace.loadingViewer': '正在加载 3D 查看器…',
  'design.kind.concept': '概念方案',
  'design.kind.variant': '方案变体',
  'design.status.exploring': '探索中',
  'design.status.candidate': '候选',
  'design.status.review': '评审中',
  'design.status.approved': '已批准',
  'design.status.rejected': '已淘汰',
  'design.status.archived': '已归档',
  'save.saving': '正在保存…',
  'save.saved': '已保存',
  'save.failed': '保存失败',
  'save.failedPreserved':
    '保存失败，当前编辑尚未保存。请先重试，关闭或刷新可能丢失编辑；原有已保存数据未被修改。{error}',
  'save.retry': '重试保存',
  'archive.error.conflict':
    '该文件与其他本地工程的标识冲突，未替换任何内容。请从来源工程导出独立副本后重试。',
  'archive.error.tooLarge': '文件或解压后的内容超过安全上限。请精简工程后重新导出再试。',
  'archive.error.corrupt': '文件已损坏，或不是 .oidproj 工程包。请重新下载或导出完整文件。',
  'archive.error.path': '工程包包含不安全的文件路径。请使用本软件正式导出的工程包。',
  'archive.error.manifest': '工程格式信息缺失或无效。请从来源软件重新导出。',
  'archive.error.version': '当前软件不支持此工程版本。请使用兼容版本打开，不要手动修改版本号。',
  'archive.error.data': '工程数据或关联关系不完整。请恢复可靠备份，或从来源工程重新导出。',
  'archive.error.missingAsset': '工程包缺少图片或其他资源文件。请包含本地素材重新完整导出。',
  'archive.error.storage': '工程包使用了不支持的素材存储方式。请导出包含本地资源的工程副本。',
  'archive.error.secrets': '工程包含凭据字段。请在来源软件移除凭据后重新安全导出。',
  'archive.error.unknown': '未能完成操作。请保持当前页面，检查本地存储是否可用后再试。',
  'dialog.projectName': '项目名称',
  'dialog.boardName': '画板名称',
  'dialog.conceptName': '概念方案名称',
  'dialog.nameNew': '命名新{item}',
  'dialog.rename': '重命名{item}',
  'dialog.project': '项目',
  'dialog.board': '画板',
  'dialog.concept': '概念方案',
  'dialog.projectDescription': '项目用于组织画板、资源、设计血缘和本地备份。',
  'dialog.boardDescription': '画板是项目中的专注工作区。',
  'dialog.conceptDescription': '概念方案用于在探索变体前明确工业设计方向。',
  'dialog.saveName': '保存名称',
  'inspector.title': '检查器',
  'inspector.selection': '当前选择',
  'inspector.lineage': '设计血缘',
  'inspector.review3d': '3D 评审',
  'inspector.noneTitle': '未选择内容',
  'inspector.noneDescription': '选择卡片以查看其设计意图、资源和可用操作。',
  'inspector.basic': '基本信息',
  'inspector.type': '类型',
  'inspector.position': '位置',
  'inspector.size': '尺寸',
  'inspector.design': '设计信息',
  'inspector.kind': '类别',
  'inspector.decision': '决策状态',
  'inspector.lineageField': '血缘',
  'inspector.variantOf': '源自 {name} 的方案变体',
  'inspector.missingParent': '暂不可用的源方案',
  'inspector.approved': '已批准的设计',
  'inspector.readyCad': '可进入 CAD',
  'inspector.dna': 'Design DNA',
  'dna.hint':
    '选择后续探索需要保留的属性。保存不会生成图片或修改已有变体；这些是模型指令，不是几何锁定保证。',
  'dna.silhouetteLocked': '保留整体轮廓',
  'dna.proportionLocked': '保留产品比例',
  'dna.geometryLocked': '保留主体结构',
  'dna.detailLocked': '保留特征细节',
  'dna.cmfLocked': '保留颜色、材质与表面处理',
  'dna.brandLocked': '保留品牌特征',
  'dna.notes': '补充约束（每行一项）',
  'dna.save': '保存设计约束',
  'dna.saved': '设计约束已保存，已有结果可能基于旧输入。',
  'dna.failed': '设计约束保存失败，草稿已保留，请重试。',
  'dna.limit': '最多 40 行、4,000 个字符。',
  'inspector.locked': '已锁定',
  'inspector.open': '开放',
  'inspector.aiActions': 'AI 操作',
  'inspector.aiDescription': '分析和生成始终保留所选的源方案。',
  'inspector.openAi': '打开 AI 操作',
  'inspector.cmf': 'CMF',
  'inspector.cmfDescription': '材料与表面处理附属于所选方案，而不是这张画布卡片。',
  'inspector.view3d': '视图 / 3D',
  'inspector.preview': '预览',
  'inspector.captured': '已捕捉',
  'inspector.noCapture': '尚未捕捉',
  'inspector.view': '视图',
  'inspector.model': '模型',
  'candidate.title': '候选托盘',
  'candidate.description': '生成的候选会保留在此处，只有明确采纳后才会成为方案变体。',
  'candidate.loading': '正在生成候选…',
  'candidate.empty': '没有可供评审的候选。',
  'candidate.previewUnavailable': '候选预览不可用',
  'candidate.keep': '采纳为方案变体',
  'provider.title': 'AI 模型连接设置',
  'provider.description': '使用自己的 API Key 连接 OpenAI 兼容服务，使用文本、视觉和图像生成能力。',
  'provider.add': '添加模型连接',
  'provider.name': '名称',
  'provider.baseUrl': '基础 URL',
  'provider.model': '模型 ID',
  'provider.apiKey': 'API Key',
  'provider.keepKey': '留空可保留现有 Key。',
  'provider.pasteKey': '粘贴 API Key',
  'provider.remember': '在此浏览器本地记住此 Key',
  'provider.privacy':
    '仅会话的 Key 会在页面关闭后消失；记住的 Key 只保存在本地浏览器中，绝不会进入项目文件。',
  'provider.save': '保存模型连接',
  'provider.test': '测试连接',
  'provider.keyChecking': '正在检查本地凭据…',
  'provider.keyAvailable': '已有本地 Key，可直接测试连接，无需再次输入。',
  'provider.testKeyRequired': '请输入 API Key 后测试连接，当前没有可用的本地 Key。',
  'provider.delete': '删除模型连接',
  'provider.defaultName': 'OpenAI 兼容服务',
  'ai.title': 'AI 工作台',
  'ai.sourceDesign': '当前方案',
  'ai.manageProvider': '配置',
  'ai.description': '只有所选设计方案和此提示词会发送给选定的模型服务；AI 不会覆盖源方案。',
  'ai.provider': '模型连接',
  'ai.chooseProvider': '选择模型连接',
  'ai.notConfigured': '尚未配置模型连接。请打开配置，填写你自己的 API Key。',
  'ai.checking': '正在检查本地 API Key…',
  'ai.missingKey': '此模型连接缺少 API Key。请先在连接设置中添加，再运行 AI 操作。',
  'ai.prompt': '提示词或设计师备注',
  'ai.selectDesign': '请先选择一张设计方案卡片，再使用 AI 操作。',
  'ai.selectedDesign': '已选择方案：{name}',
  'ai.analyzing': '正在分析…',
  'ai.analyze': '分析设计',
  'ai.generating': '正在生成…',
  'ai.generate': '生成方案变体',
  'ai.renderUnavailable': '草图渲染需要支持图像编辑的模型，当前暂不可用。',
  'ai.latestAnalysis': '最近一次分析',
  'ai.defaultPrompt': '探索更精炼的便携灯设计方向。',
  'feedback.unknownStorage': '未知的本地存储错误。',
  'feedback.unknown': '未知错误。',
  'feedback.boardRequired': '项目至少需要一个画板。',
  'feedback.deleteProjectConfirm': '要删除“{name}”及其全部本地资源吗？',
  'feedback.deleteBoardConfirm': '要删除画板“{name}”及其画布节点吗？',
  'feedback.referenceImportFailed': '无法导入参考图。',
  'feedback.demoUnavailable': '示例图片加载失败，请重新打开示例项目。',
  'feedback.exported': '项目备份已准备好，请检查浏览器下载。',
  'feedback.downloadBackup': '再次下载备份',
  'feedback.exportFailed': '导出失败：{error}',
  'feedback.imported': '项目已导入并恢复。',
  'feedback.importFailed': '导入失败：{error}',
  'feedback.providerSaved': '模型连接设置已保存。',
  'feedback.providerSaveFailed': '无法保存模型连接：{error}',
  'feedback.connecting': '正在连接…',
  'feedback.connectionVerified': '连接已验证。',
  'feedback.connectionFailed': '连接测试失败：{error}',
  'feedback.providerDeleted': '模型连接已删除。',
  'feedback.designProviderRequired': '请先选择设计方案并配置模型连接。',
  'feedback.analysisCompleted': '设计分析已完成。',
  'feedback.analysisFailed': '设计分析失败。',
  'feedback.candidateGenerated': '候选已生成。请先在候选托盘中评审，再决定是否保留。',
  'feedback.variantFailed': '方案变体生成失败。',
  'feedback.variantCreated': '已从所选候选创建新的方案变体。',
  'feedback.candidateKeepFailed': '无法保留生成的候选。',
  'feedback.modelMissing': '本地存储中缺少所选模型文件。',
  'feedback.modelOpenFailed': '无法打开 3D 模型：{error}',
  'feedback.modelImportFailed': '模型导入失败：{error}',
  'feedback.viewerSaveFailed': '无法保存查看器状态：{error}',
  'feedback.captureSaved': '预览已捕捉并作为图像 Asset 保存在本地。',
  'feedback.captureFailed': '无法保存捕捉结果：{error}',
  'feedback.deleteProviderConfirm': '要删除模型连接“{name}”及其在本地记住的 API Key 吗？',
  'feedback.storageUnavailable':
    '本地存储不可用。现有数据未被修改。请检查 IndexedDB / 网站存储后重新加载。({error})',
  'feedback.storageProjectsUnavailable':
    '本地存储不可用，无法加载项目。请检查 IndexedDB / 网站存储后重新加载。({error})',
  'action.failed': '操作失败。',
  'action.empty': '当前选择没有可用操作。',
  'action.palette': '命令面板',
  'action.commands': '命令',
  'action.search': '搜索可用操作',
  'action.selection': '选择操作',
  'action.workspace.duplicate.label': '复制所选内容',
  'action.workspace.duplicate.description': '创建所选画布节点的错位副本。',
  'action.workspace.delete.label': '删除所选内容',
  'action.workspace.delete.description': '删除所选画布节点。',
  'action.design.variant.label': '创建方案变体',
  'action.design.variant.description': '从所选方案创建子方案及其画板卡片。',
  'action.ai.text.label': '生成文本',
  'action.ai.text.description': '通过已配置的模型无关能力路由生成文本。',
  'action.ai.test.label': '测试模型连接',
  'action.ai.test.description': '验证已配置的模型连接和 API Key，不修改项目数据。',
  'action.ai.analyze.label': '分析设计方案',
  'action.ai.analyze.description': '请求已配置的 AI 分析所选方案，不做修改。',
  'action.ai.variant.label': '生成方案变体',
  'action.ai.variant.description': '为新的方案变体生成候选，不修改源方案。',
  'action.ai.keep.label': '保留已生成候选',
  'action.ai.keep.description': '从所选 AI 候选创建新的方案变体。',
  'sketch.workspace': '草图工作区',
  'sketch.subtitle': '绘制并完善设计想法',
  'dialog.saveFailed': '未能保存，已保留输入，请重试。',
  'sketch.saveFailed': '草图未能保存。画面仍在此处，请重试。',
  'sketch.edit': '编辑原始草图',
  'sketch.staticHint':
    '这是静态草图参考，没有可编辑原稿。仍可作为生成输入；如需绘制，请从顶部“草图”新建可编辑草图。',
  'sketch.sharedHint': '复制的草图卡片共用原稿。保存会同步它们的预览，不改变各卡片的位置和连线。',
  'sketch.loadFailed': '找不到有效的可编辑草图源文件，已有预览未被修改。',
  'threeD.workspace': '3D 工作区',
  'threeD.import': '导入 GLB / GLTF',
  'threeD.model': '模型',
  'threeD.chooseModel': '选择本地模型',
  'threeD.return': '返回工作区',
  'threeD.title': '3D 查看器',
  'threeD.empty': '导入 GLB / GLTF 模型，或在工作区中选择 3D 卡片后在这里打开。',
  'threeD.camera': '相机',
  'threeD.perspective': '透视',
  'threeD.orthographic': '正交',
  'threeD.presets': '标准视角',
  'threeD.front': '前视',
  'threeD.side': '侧视',
  'threeD.rear': '后视',
  'threeD.top': '顶视',
  'threeD.fit': '适配对象',
  'threeD.reset': '重置视图',
  'threeD.grid': '网格',
  'threeD.ground': '地面',
  'threeD.wireframe': '线框',
  'threeD.capture': '捕捉当前视图',
  'threeD.controls': '旋转：左键拖动 · 平移：右键拖动 · 缩放：滚轮',
  'threeD.info': '模型信息',
  'threeD.file': '文件',
  'threeD.format': '格式',
  'threeD.meshes': '网格数',
  'threeD.bounds': '包围盒',
  'threeD.previewUnavailable': '模型预览不可用。',
  'threeD.loadFailed': '模型加载失败，文件仍已保存。请重试或选择其他模型。',
  'threeD.retry': '重新加载',
  'canvas.workspace': '工作区画布',
  'canvas.emptyTitle': '从一张参考图或一个想法开始',
  'canvas.emptyDescription': '导入图片收集灵感，或新建概念方案记录设计意图。不需要先配置 AI。',
  'canvas.emptyHint': '再从方案展开不同方向、比较结果。只有点击“生成”才会运行 AI。',
  'canvas.derivedFrom': '源自 {name}',
  'canvas.derived': '派生设计',
  'node.text': '备注',
  'node.image': '图片',
  'node.reference': '参考图',
  'node.sketch': '草图',
  'node.concept': '概念方案',
  'node.variant': '方案变体',
  'node.viewset': '多视图',
  'node.cmf': 'CMF',
  'node.model3d': '3D 评审',
  'node.group': '分组',
  'node.generation': '生成',
  'generation.direction': '设计方向',
  'generation.tool.change': '切换任务',
  'generation.batch.title': '批量探索',
  'generation.queue.title': '运行任务队列',
  'generation.batch.references': '共享参考图（可选，最多 4 张）',
  'generation.batch.referencesHint':
    '每个任务都会读取这些真实连接的图片。主图不能同时作为共享参考；创建任务不会发送请求。',
  'generation.queue.hint':
    '最多选择 16 个已保存任务，按选择顺序执行。确认前请检查输入；失败即停止，已完成结果保留。关闭或刷新不会自动续跑。',
  'generation.queue.tasks': '待运行任务',
  'generation.queue.summary': '{tasks} 个任务 · 最多 {images} 张结果',
  'generation.queue.cost': '生成费用由所选服务商收取；取消不保证免除已发请求的费用。不会自动重试。',
  'generation.queue.run': '确认并运行队列',
  'generation.queue.running': '正在运行',
  'generation.queue.success': '已完成',
  'generation.queue.cancelled': '已取消',
  'generation.queue.failed': '队列已停止，已完成结果保留。请检查失败任务，再手动开始新的队列。',
  'generation.queue.complete': '所选任务已全部完成，请在画布评审结果。',
  'generation.batch.hint':
    '按“主图 × 设计方向”准备独立任务。这一步只保存草稿，不调用模型；检查输入后再手动运行各任务。',
  'generation.batch.sources': '产品主图（1–4 张）',
  'generation.batch.sharedBrief': '共同设计要求（可选）',
  'generation.batch.sharedBriefHint':
    '系列化探索可在这里描述共同轮廓、材质与细节语言，各方向填写产品差异。创建时复制到每个任务，之后独立编辑、不联动；模型的一致性仍需评审。',
  'generation.batch.briefLimit': '共同要求与任一方向合计不能超过 10000 字符，请缩短要求或方向。',
  'generation.batch.directions': '设计方向（1–4 个）',
  'generation.batch.name': '方向 {number} 名称',
  'generation.batch.remove': '移除此方向',
  'generation.batch.add': '添加方向',
  'generation.batch.count': '每个任务的结果数量',
  'generation.batch.summary': '{tasks} 个任务 · 计划 {images} 张结果。准备时不发起生成请求。',
  'generation.batch.prepare': '在画布准备任务',
  'generation.batch.failed': '批量保存失败，未保留部分任务。请检查输入与本地存储后重试。',
  'generation.tool.custom': '自定义任务',
  'generation.tool.patternCreate': '图案生成',
  'generation.tool.patternCreateHint':
    '从文字或已连接参考图生成平面图案。连续纹样只向模型提出拼接要求，仍需检查接缝。',
  'generation.prompt.patternCreate': '生成平面装饰图案，请描述主题元素、配色与视觉风格。',
  'generation.tool.patternTransfer': '图案迁移',
  'generation.tool.patternTransferHint':
    '连接一张产品主图和一张图案参考，由 AI 理解位置与比例；精确平面定位请用图案定位。',
  'generation.prompt.patternTransfer': '将参考图案应用到产品上，保留产品身份、几何结构与功能细节。',
  'generation.patternTask.input': '图案输入方式',
  'generation.patternTask.text': '仅文字起稿',
  'generation.patternTask.images': '使用已连接参考图',
  'generation.patternTask.repeat': '图案布局',
  'generation.patternTask.single': '独立图案',
  'generation.patternTask.tile': '连续纹样（需检查接缝）',
  'generation.patternTask.placement': '目标部件／应用位置',
  'generation.patternTask.scale': '图案相对比例',
  'generation.patternTask.small': '小比例',
  'generation.patternTask.medium': '中等比例',
  'generation.patternTask.large': '大比例',
  'generation.patternTask.required':
    '请连接一张产品主图和一张图案参考，并填写目标部件；这些是 AI 指令，不保证精确曲面贴合。',
  'generation.tool.localCmf': '局部 CMF',
  'generation.tool.localCmfHint': '选择部件区域，指定颜色、材质或表面处理；选区外保留原图像素。',
  'generation.prompt.localCmf': '仅改变选中部件的 CMF，保留产品几何结构与功能细节。',
  'generation.localCmf.color': '目标颜色',
  'generation.localCmf.material': '目标材质',
  'generation.localCmf.finish': '目标表面处理',
  'generation.localCmf.fieldsHint':
    '至少填写一项；留空项要求保留原样。选区内的模型保真度仍需评审。',
  'generation.tool.text': '文生创意',
  'generation.tool.textHint': '从文字起稿，无需输入图片或已有方案；生成独立候选后再决定采纳。',
  'generation.prompt.text': '设计一个产品概念，请描述它的功能、造型、材质与使用场景。',
  'generation.text.disconnect': '切换文生创意前请先明确断开输入图片，不会悄悄忽略已有图片。',
  'generation.intent': '探索意图',
  'generation.tool.label': '设计工具',
  'generation.tool.view': '视角探索',
  'generation.tool.viewHint':
    '将产品连为主图，最多选择四个视角。各视角分别读取相同输入生成；几何一致性仍取决于模型。',
  'generation.view.batch':
    '将发送 {count} 次图像编辑请求，每个视角一次，服务商分别计费。不自动重试；全部成功后才保存本组候选。',
  'generation.prompt.view':
    '从不同相机角度展示同一个产品。保留产品造型、比例、细节及 CMF，使用中性影棚背景。',
  'generation.view.label': '目标视角',
  'provider.supportsMask': '此服务和模型支持图像编辑蒙版',
  'provider.maskHint': '请查阅服务文档后启用。测试连接不等于已验证蒙版支持。',
  'generation.tool.local': '局部编辑',
  'generation.tool.erase': '智能消除',
  'generation.tool.cutout': '智能抠图',
  'generation.tool.pattern': '图案定位',
  'generation.tool.patternHint': '精确定位图片或透明图案。本地平面合成，不是自动曲面贴合。',
  'generation.prompt.pattern': '将参考图案定位到主图产品上。',
  'generation.pattern.help':
    '在预览中拖动定位图案中心，下方调整尺寸、旋转和透明度。建议使用透明 PNG 图案。',
  'generation.pattern.inputs': '连接一张主图和一张图案参考图。',
  'generation.pattern.local': '仅本地合成，无需 API Key，不发模型请求、不产生服务商费用。',
  'generation.pattern.run': '创建合成候选',
  'generation.pattern.x': '水平中心（%）',
  'generation.pattern.y': '垂直中心（%）',
  'generation.pattern.width': '宽度（%）',
  'generation.pattern.height': '高度（%）',
  'generation.pattern.rotation': '旋转（°）',
  'generation.pattern.opacity': '不透明度（%）',
  'generation.tool.cutoutHint':
    '保留原图产品颜色，仅采用返回图的透明蒙版。不透明、全透明或尺寸不一致的结果会被拒绝；采纳前请检查轮廓。',
  'generation.prompt.cutout': '移除背景，保留完整产品及原来的位置和图片尺寸。',
  'generation.cutout.required': '仅连接一张主图，并在模型设置中确认支持透明 PNG 编辑输出。',
  'provider.supportsTransparency': '此服务和模型支持透明 PNG 编辑输出',
  'generation.tool.eraseHint':
    '选中要移除的对象，发送真实蒙版并保护选区外像素。背景补全依赖模型能力；请评审候选后再采纳。',
  'generation.prompt.erase': '移除选区中的对象或细节，自然补全周围表面或背景，不要加入替代物。',
  'generation.tool.localHint':
    '在主图上框选区域，再描述修改内容。发送真实透明蒙版，结果只合入选区内；尺寸不一致时拒绝保存。选区内的修改质量取决于模型。',
  'generation.prompt.local':
    '根据下方说明修改主图产品的选中区域。保留选区以外的结构、材质、光线与背景。',
  'generation.mask.title': '修改选区',
  'generation.mask.tool': '选区工具',
  'generation.mask.rectangle': '矩形',
  'generation.mask.polygon': '多边形',
  'generation.mask.brush': '画笔',
  'generation.mask.diameter': '画笔直径（图片短边比例）',
  'generation.mask.polygonHelp': '沿轮廓点击添加顶点，再点击完成选区。Esc 取消尚未完成的顶点。',
  'generation.mask.finish': '完成选区',
  'generation.mask.undoPoint': '撤销顶点',
  'generation.mask.undoStroke': '撤销最后一笔',
  'generation.mask.limit': '已达到选区复杂度上限，请撤销笔画或简化轮廓。',
  'generation.mask.protectionFailed':
    '局部编辑无法安全合成：返回图片无法读取，或尺寸与原图不一致。未保存候选，也未自动重试。',
  'generation.compareMode': '对比方式',
  'generation.compareSource': '主图对照',
  'generation.compareCandidates': '候选并排',
  'generation.compareWith': '对照候选',
  'generation.reviewTarget': '当前操作对象：{name}',
  'generation.mask.loading': '正在加载主图…',
  'generation.mask.precision': '精确调整选区',
  'generation.mask.x': '左侧位置（%）',
  'generation.mask.y': '顶部位置（%）',
  'generation.mask.width': '宽度（%）',
  'generation.mask.height': '高度（%）',
  'generation.mask.help':
    '用矩形、多边形或画笔选择要修改的部位。只将蓝色区域合入结果，选区外保留原图像素。请选中完整部件，并留出边缘余量。',
  'generation.mask.selected': '选区已保存。更换主图素材后需要重新框选。',
  'generation.mask.clear': '清除选区',
  'generation.mask.mainRequired': '请先连接有预览的主图，再框选修改区域。',
  'generation.mask.providerRequired': '请在模型连接设置中确认所选模型支持蒙版，再运行局部编辑。',
  'generation.view.request':
    '目标视角：{view}。每张图片只展示一个产品视图，不生成拼图。候选均为该视角的不同表达。保留产品特征、结构与 CMF，不重新设计产品。',
  'generation.view.front': '正面',
  'generation.view.side': '侧面',
  'generation.view.rear': '背面',
  'generation.view.top': '俯视',
  'generation.view.perspective': '透视',
  'generation.tool.choose': '选择任务方向…',
  'generation.tool.limit':
    '效果与一致性取决于所选模型。局部编辑和消除使用真实选区蒙版，其他方向为可编辑任务模板。选择工具会替换下方设计方向，不会发起请求。',
  'generation.tool.sketch': '草图渲染',
  'generation.tool.lineart': '产品线稿提取',
  'generation.tool.lineartHint':
    '将产品图片连为主图，生成可调整方向的栅格线稿；不是矢量描摹或 CAD 几何。',
  'generation.prompt.lineart':
    '从产品主图提取清晰的工业设计线稿。保留轮廓、比例、视角、零件分界及功能细节；用白色背景和有层次的深色轮廓线表达，去除材质颜色、纹理、反射、投影和环境杂物。不要重新设计产品，不要臆造不可见几何，不要添加标注、尺寸或额外视角。补充参考仅用于线条粗细风格，不得替换主图产品。输出一张可作为草图参考的栅格线稿，不是 CAD 或矢量文件。',
  'generation.tool.sketchHint': '将草图连为主图，补充材质或渲染参考。',
  'generation.tool.blend': '造型融合',
  'generation.tool.blendHint': '以产品作为主图，连接另一种造型作为参考。',
  'generation.tool.style': '设计语言迁移',
  'generation.tool.styleHint': '保留产品特征，用参考图表达希望借鉴的设计语言。',
  'generation.tool.formHint': '保留功能意图，探索不同轮廓与造型方向。',
  'generation.tool.cmfHint': '保留结构，连接材料、色彩或表面处理参考。',
  'generation.tool.sceneHint': '保留产品特征，描述合理的使用环境。',
  'generation.prompt.sketch':
    '将主图草图转化为工业设计效果图。保留草图轮廓、比例与功能结构。参考图仅用于材质、光线与渲染表达，不用参考产品替换草图方案。',
  'generation.prompt.blend':
    '保留主图产品的功能与关键比例，提取参考图中的造型特征，融合成统一的新方案，而非简单拼贴。保持结构合理，明确表达与源方案不同的设计方向。',
  'generation.prompt.style':
    '保留主图产品的特征、功能与比例。借鉴参考图的曲面、细节与过渡方式，将其转化为协调的设计语言，不复制参考图的品牌，也不替换主图产品。',
  'generation.setup': '运行设置',
  'generation.review': '先比较，再采纳。源方案始终保持不变。',
  'generation.mask.protectionHint':
    '选区外像素保持不变；模型仍可能改变选区内结构。请完整框住目标部件，并留少量边距。',
  'generation.mask.reviewHint':
    '请求完成不代表修改符合要求。采纳前，请与原图对照检查部件形状、材质和选区边缘接缝。',
  'generation.presets': '方向起点 · 可自由修改，不会自动生成',
  'generation.preset.form': '探索造型',
  'generation.preset.cmf': '探索 CMF',
  'generation.preset.scene': '场景表达',
  'generation.prompt.form':
    '保留产品功能与关键比例，结合已连接的参考素材，探索有明确特征且统一的造型语言。',
  'generation.prompt.cmf':
    '保留产品轮廓与结构，结合已连接的参考素材，探索协调的材料、色彩与表面处理方向。',
  'generation.prompt.scene':
    '保留产品特征与比例，在合理的使用场景中表达产品，保持光线、尺度与环境协调。',
  'generation.viewCandidate': '查看候选大图',
  'generation.compare': '候选对比评审',
  'generation.source': '当前主图输入',
  'generation.candidateNumber': '候选 {number}',
  'generation.disconnect': '断开 {name} 的输入连接',
  'generation.discardReferenced': '此结果正被后续步骤使用，请先断开后续输入连接，再丢弃。',
  'generation.notes': '补充说明',
  'generation.count': '生成数量',
  'generation.run': '生成',
  'generation.configure': '配置模型',
  'generation.cardProvider': '模型：{name} · {count} 张',
  'generation.cardProviderMissing': '尚未配置模型',
  'generation.running': '正在生成…',
  'generation.cancel': '取消生成',
  'generation.cancelled': '已取消生成。服务商仍可能收取已开始处理的费用。',
  'generation.ready': '等待生成',
  'generation.stale': '输入已变化，以下结果基于旧输入',
  'generation.failed': '生成失败',
  'generation.providerRequired': '请先配置支持图像编辑的模型连接和 API Key。',
  'generation.noInputs': '请至少连接一张图片、草图、概念方案或方案变体。',
  'generation.billing': '生成图像的费用由所选模型服务商收取。',
  'generation.selectSource': '从素材卡片右侧圆点拖到生成节点的「主图」或「参考图」端口。',
  'generation.base': '主图',
  'generation.reference': '参考图',
  'generation.connected': '已连接 {count} 张图片',
  'generation.candidates': '候选方案',
  'generation.selectedOnCanvas': '画布中选中',
  'generation.resultSelection': '候选结果',
  'generation.openStep': '查看生成步骤',
  'generation.continueExploration': '继续探索',
  'generation.moreTools': '更多图片工具',
  'generation.manualStepHint': '选择操作后自动带入当前图片；只有点击生成才会运行。',
  'generation.stepSource': '来源步骤与要求',
  'generation.keepDesign': '采纳为设计方案',
  'generation.keepReference': '保存为参考图',
  'generation.previewUnavailable': '候选预览不可用',
  'generation.generatedConceptName': '生成概念方案',
  'generation.generatedVariantName': '{name} · 方案变体',
  'generation.generatedReferenceName': '生成参考图',
};

const messages: Record<AppLocale, Record<MessageKey, string>> = {
  en: englishMessages,
  'zh-CN': simplifiedChineseMessages,
};

export function resolveAppLocale(value?: string | null): AppLocale {
  return value?.toLocaleLowerCase().startsWith('zh') ? 'zh-CN' : 'en';
}

export function translate(
  locale: AppLocale,
  key: MessageKey,
  variables: Record<string, string | number> = {},
): string {
  return messages[locale][key].replace(/\{(\w+)\}/g, (_, name: string) =>
    String(variables[name] ?? ''),
  );
}

export function translateDesignKind(locale: AppLocale, kind: 'concept' | 'variant') {
  return translate(locale, `design.kind.${kind}` as MessageKey);
}

export function translateGraphRelation(locale: AppLocale, type: string) {
  const key = `graph.relation.${type}` as MessageKey;
  return key in englishMessages
    ? translate(locale, key)
    : translate(locale, 'graph.relation.related_to');
}

export function translateDesignStatus(
  locale: AppLocale,
  status: 'exploring' | 'candidate' | 'review' | 'approved' | 'rejected' | 'archived',
) {
  return translate(locale, `design.status.${status}` as MessageKey);
}

export function translateNodeType(
  locale: AppLocale,
  nodeType:
    | 'text'
    | 'image'
    | 'reference'
    | 'sketch'
    | 'concept'
    | 'variant'
    | 'viewset'
    | 'cmf'
    | 'model3d'
    | 'group'
    | 'generation'
    | 'candidate',
) {
  if (nodeType === 'candidate') return translate(locale, 'generation.resultSelection');
  return translate(locale, `node.${nodeType}` as MessageKey);
}

/** Presentation-only labels for the built-in demo data; persisted values remain unchanged. */
export function translateDemoLabel(locale: AppLocale, value: string | undefined) {
  if (typeof value !== 'string') return '';
  if (locale !== 'zh-CN') return value;
  const labels: Record<string, string> = {
    'Untitled project': '未命名项目',
    'Portable Lamp Demo': '便携灯具示例',
    'Demo Project': '示例项目',
    Reference: '参考图',
    Sketch: '草图',
    Concept: '概念探索',
    Variant: '方案变体',
    '3D Model': '3D 评审',
    'Multi-view': '多视图',
    'View Set': '多视图',
    Image: '图片',
    Text: '备注',
    Group: '分组',
    'portable lamp': '便携灯具',
    'working study': '工作探索',
    'softened silhouette': '柔和轮廓',
    'Portable lamp exploration': '便携灯具探索',
    'Portable lamp concept': '便携灯具概念方案',
    'Softened silhouette': '柔和轮廓',
    'Sketch — working study': '草图探索',
    'Sketch scene': '草图场景',
    'Sketch preview.png': '草图预览.png',
  };
  const prefixes: Array<[string, string]> = [
    ['Reference — ', '参考图 · '],
    ['Sketch — ', '草图 · '],
    ['Concept — ', 'Concept · '],
    ['Variant — ', 'Variant · '],
    ['3D Model — ', '3D · '],
  ];
  const prefix = prefixes.find(([source]) => value.startsWith(source));
  if (prefix) {
    const suffix = value.slice(prefix[0].length);
    return `${prefix[1]}${labels[suffix] ?? suffix}`;
  }
  return labels[value] ?? value;
}
